.compile_template: &compile_definition
  tags:
    - docker
  script:
    - l3build ctan
  stage: build
  artifacts:
    paths:
      - build/distrib/ctan/rebuttal/
  needs: []

compile:texlive2022:
  image: sergiud/texlive:2022
  <<: *compile_definition

compile:texlive2023:
  image: sergiud/texlive:2023
  <<: *compile_definition

compile:texlive2024:
  image: sergiud/texlive:2024
  <<: *compile_definition
