# SPDX-FileCopyrightText: 2026 Sergiu Deitsch
# SPDX-License-Identifier: LPPL-1.3c+

version = 1

[[annotations]]
path = "announcement"
SPDX-FileCopyrightText = "2026 Sergiu Deitsch"
SPDX-License-Identifier = "LPPL-1.3c+"

[[annotations]]
path = "testfiles/*.tlg"
SPDX-FileCopyrightText = "2026 Sergiu Deitsch"
SPDX-License-Identifier = "LPPL-1.3c+"
